name: Create RTC Links workflow

on: [push, pull_request]
jobs:
  rtc-links-creation:
    runs-on: [bcn,test] 

    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2
      - name: Invoke RTC endpoint
        uses: ./.github/actions/RtcLinker
        with:
            GH_EVENT_JSON: ${{ toJSON(github.event) }}
            RTC_HOST: "rb-alm-11-d.de.bosch.com/ccm/service/com.ibm.team.git.common.internal.IGitHubInvokeService?repokey=e1b57600c43a4c6481de0bf85bc96324&rtcUser=NBD5KOR"
            HEADER_GITHUB_EVENT: ${{ github.event_name }}